### ISSUE TITLE
cacheNot property doesn´t work

### ISSUE THREAD

**Issue by frodfigu** [FokkeZB/nl.fokkezb.cachedImageView#10]
I have a big problem with automatic cache of imageView on iOS devices...
So, I´m adding this widget to my app but the init property cacheNot doesn´t work

```js
var args = { cacheNot: true };
		
var myPhoto = Alloy.createWidget("cachedImageView", null, args);
myPhoto.applyProperties({
	width : 160,
	height : 120,
	image : thumbURL,
	touchEnabled : false
});
```

What I´m doing wrong?

**Comment by FokkeZB** [comment]
Hi, the widgets doesn't persist the properties. You'll need to pass cacheNot to applyProperties (as well).

**Comment by frodfigu** [comment]
Sorry, but doesn´t work passing cacheNot to applyProperties...

:-(

Can you help me?

**Comment by FokkeZB** [comment]
Could you share a full example project?

**Comment by frodfigu** [comment]
OK, here is the code that doesn´t work

```js
var myPhoto = Alloy.createWidget("cachedImageView");
	myPhoto.applyProperties({
        cacheNot : true
	width : 160,
	height : 120
});
```

Adding a photo DSC_001.JPG works fine
After remove a DSC_001.JPG my camera create a new photo file named DSC_001.JPG it´s not the same photo.

This above code shows me the older DSC_001.JPG photo, not the new.

Why Titanium not compare the headers and load the new image if the cached image it´s not the same?

**Comment by FokkeZB** [comment]
He @frodfigu did you actually try this code? Because if you copy-pasted it, there's a crucial `,` missing after `cacheNot: true`.

**Comment by frodfigu** [comment]
Yeah, it´s doesn´t the problem. Sorry. I´m writing here. So... How can I solve my problem? Do you know?

**Comment by FokkeZB** [comment]
I think I know what's happening. The widget skips caching, but Titanium itself will still cache. You will have to add a query string to the URL to force it to fetch a new one.
